export class Weapon {
    name: string;
    damage: number;
    constructor (name: string,damage: number) {
        this.name = name;
        this.damage = damage;
    }
}

const weapons = [
    new Weapon("Big Bonk",3),
    new Weapon("Spork",1),
    new Weapon("Comically Oversized Mallet",5),
    new Weapon("Butter Knife",3),
    new Weapon("Tuning Fork",5),
    new Weapon("Long Sword",6),
    new Weapon("Whip",2),
    new Weapon("Bowling Pin",2),
    new Weapon("Bowling Ball",4),
    new Weapon("Blade of Grass",2),
    new Weapon("Pitchfork",3),
    new Weapon("Inflatable Baseball Bat",1),
    new Weapon("Fire Punch",6),
    new Weapon("Ice Punch",4),
    new Weapon("Thunder Punch",4),
    new Weapon("Frozen Meat Knife",5),
    new Weapon("Fingergun",6),
    new Weapon("Treebuchet",4),
    new Weapon("Dried Date",10),
    new Weapon("Sack of Potatoes",4),
    new Weapon("Very Short Sword",5),
    new Weapon("Minigun",7),
    new Weapon("Ping-Pong Paddle",3),
    new Weapon("Jar",3),
    new Weapon("Mace",3),
    new Weapon("Bow and Arrow",3),
    new Weapon("Plasma Rifle",4),
    new Weapon("Chaingun",5),
    new Weapon("Super Shotgun",7),
    new Weapon("Wii-Fit Balance Board",2),
    new Weapon("Pair of Nunchucks",4),
    new Weapon("Pair of Wii Nunchucks",2),
    new Weapon("Fuel Rod Cannon",6),
    new Weapon("Gravity Hammer",6),
    new Weapon("Gauss Cannon",7),
    new Weapon("Needler",3),
    new Weapon("Netherite Hoe",5),
    new Weapon("Crossbow",5),
    new Weapon("Ballista",6),
    new Weapon("Railgun",6),
    new Weapon("Hwacha",5),
    new Weapon("Slime Pickaxe",3),
    new Weapon("Nuclear Pickaxe",6),
    new Weapon("Regular Punch",2),
    new Weapon("Copy of Shaun Spalding's Collision Code",10),
    new Weapon("Sticky Bomb Launcher",6),
    new Weapon("Large Wrench",4),
    new Weapon("Portal Gun",5),
    new Weapon("Gravity Gun",5),
    new Weapon("Crowbar",4),
    new Weapon("Lightsaber",7),
    new Weapon("Hot Take",2),
    new Weapon("Hot Wheels Track",4),
    new Weapon("Batarang",5),
    new Weapon("Chopstick",3),
    new Weapon("Uncomfortable Hug",4),
    new Weapon("Fish Slap",4),
    new Weapon("TypeError",4),
    new Weapon("Rubber Chicken",4),
    new Weapon("`null`",4),
    new Weapon("Dobonhonkero",4),
    new Weapon("Fossilized Copy of GM8",5),
    new Weapon("Pirated Copy of GMS2",5),
    new Weapon("Clone of Mark Overmars",5),
    new Weapon("Army of Five-Year Olds",7),
    new Weapon("Large Bone", 4),
    new Weapon("Dual Quaternion",6),
    new Weapon("View Matrix",4),
    new Weapon("Shader Fragment",4),
    new Weapon("Large 1.4 Script",4),
    new Weapon("Wet Sock",4),
    new Weapon("GM Commandment Stone",4),
    new Weapon("Gamer Chair",5),
    new Weapon("Blinding RGB Lights",3),
    new Weapon("Folding Chair",6),
    new Weapon("health-- call",1),
    new Weapon("Gratuitous Screenshake",4),
    new Weapon("Bottle of Gamefeel Juice",3),
    new Weapon("Circular Sawblade",6),
    new Weapon("Nokia 3310",9),
    new Weapon("Undertale Fangame",3),
    new Weapon("Game That's Totally Not an Undertale Fangame",3),
    new Weapon("Katana",6),
    new Weapon("Sawgrass Sword",4),
    new Weapon("Walking Jury Table",4),
    new Weapon("YAL Doll",6),
    new Weapon("Oatmeal Raisin Cookie",2),
    new Weapon("Cold Glass of Milk",3),
    new Weapon("Loosely Weapon-Shaped Object",3),
    new Weapon("Falling Piano",7),
    new Weapon("Silent But Deadly Gas",4),
    new Weapon("Garfield Joke",2),
    new Weapon("Hot Pocket Straight From the Microwave",4),
    new Weapon("Compliment",1),
    new Weapon("Insult",4),
    new Weapon("Bad Vibe",3),
    new Weapon("Good Insult",6),
    new Weapon("Weak Karate Chop",2),
    new Weapon("Snek with a Knife",5),
    new Weapon("struct",4),
    new Weapon("Wet Finger in the Ear",5),
    new Weapon("Tickle",2),
    new Weapon("One Inch Punch",3),
    new Weapon("Sharp Object",4),
    new Weapon("Dry Stick",3),
    new Weapon("Bottle containing 8 Fluid Ounces of Mystery Liquid",8),
    new Weapon("Death Stare",3),
    new Weapon("Sidewalk Slam",5),
    new Weapon("Drop Kick",4),
    new Weapon("Shrump",3),
    new Weapon("Fanart of Mimpy",4),
    new Weapon("Birthday Greeting",3),
    new Weapon("execute_string function call",4),
    new Weapon("a a-an aa a bad case of stuttering",2),
    new Weapon("godot.dev",3),
    new Weapon("Forgotten Semicolon",3),
    new Weapon("Unsolicited DM",7),
    new Weapon("Help Question in Lounge",3),
    new Weapon("@ everyone mention",5),
    new Weapon("Huge Blue Robot",4),
    new Weapon("Mechanical Pencil",2),
    new Weapon("instance_destroy() call",4),
    new Weapon("Sad Rat",1),
    new Weapon("Grumpy Pug",6),
    new Weapon("Sick Burn",3),
    new Weapon("Red Shirt",2),
    new Weapon("Can of Pepsi",6),
    new Weapon("Unusual Facial Expression",2),
    new Weapon("Fish With Legs",5),
    new Weapon("Banhammer",9),
    new Weapon("Banhammer",9),
    new Weapon("<a:pacman_right:825657172981579806>",4)
]

export default weapons;